name: pirates
main: neo.main.Main
version: 1.0
api-version: 1.16
author: hamtser
commands:
  해적단:
    usage: /<command>
    description: 해적단 관련 커맨드
  전쟁선포:
    usage: /<command>
    description: 전쟁을 선포합니다